name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: SpiralFastLoop
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run flake8
        working-directory: SpiralFastLoop
        run: flake8 spiralfastloop tests
      - name: Run mypy
        working-directory: SpiralFastLoop
        run: mypy spiralfastloop

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: SpiralFastLoop
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pytest
        working-directory: SpiralFastLoop
        run: pytest -q
